/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xinzhihui_myndkdemo_MyNdk */

#ifndef _Included_com_xinzhihui_myndkdemo_MyNdk
#define _Included_com_xinzhihui_myndkdemo_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xinzhihui_myndkdemo_MyNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xinzhihui_myndkdemo_MyNdk_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_xinzhihui_myndkdemo_MyNdk
 * Method:    socket
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xinzhihui_myndkdemo_MyNdk_socket
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
